fix(net): apply coordinator fixes for PR #13
- Added MAC uniqueness validation per segment
- Removed clippy allow directives and resolved warnings
- Avoid silently discarded format results using std::fmt::Write
- Updated net-setup script with robust argument parsing and explicit IP forwarding reset
- Updated and expanded integration tests with env!("CARGO_MANIFEST_DIR")

Refs: LYZ-16

diff --git a/xtask/images/net-setup b/xtask/images/net-setup
--- a/xtask/images/net-setup
+++ b/xtask/images/net-setup
@@ -10,6 +10,7 @@ fi
 CMDLINE=$(cat "$CMDLINE_FILE")
 
 # Disable DAD, RA, autoconf globally and for default before interfaces are brought up
+# (DAD would otherwise start on link up)
 sysctl -qw net.ipv6.conf.all.accept_dad=0
 sysctl -qw net.ipv6.conf.default.accept_dad=0
 sysctl -qw net.ipv6.conf.all.accept_ra=0
@@ -19,22 +20,25 @@ sysctl -qw net.ipv6.conf.default.autoconf=0
 
 FWD=0
 
-# First pass: rename interfaces and configure IPs
 for arg in $CMDLINE; do
     case "$arg" in
         dylos.if=*)
             val="${arg#dylos.if=}"
             IF_NAME="${val%%,*}"
-            rest="${val#*,}"
-            MAC="${rest%%,*}"
-            rest="${rest#*,}"
-            IPV6="${rest%%,*}"
+            rest1="${val#*,}"
+            MAC="${rest1%%,*}"
+            rest2="${rest1#*,}"
+            IPV6="${rest2%%,*}"
+            
+            if [ "$val" = "$rest1" ] || [ "$rest1" = "$rest2" ] || [ -z "$IF_NAME" ] || [ -z "$MAC" ] || [ -z "$IPV6" ]; then
+                echo "net-setup: error: malformed dylos.if parameter: $arg" >&2
+                exit 1
+            fi
+            
             IPV4=""
-            case "$rest" in
-                *,*)
-                    IPV4="${rest#*,}"
-                    ;;
-            esac
+            if [ "$rest2" != "$IPV6" ]; then
+                IPV4="${rest2#*,}"
+            fi
 
             ACTUAL_IF=""
             for dir in /sys/class/net/*; do
@@ -66,15 +70,6 @@ for arg in $CMDLINE; do
             fi
             ip link set dev "$IF_NAME" up
             ;;
-        dylos.fwd=1)
-            FWD=1
-            ;;
-    esac
-done
-
-# Second pass: routes (needs interfaces to be up)
-for arg in $CMDLINE; do
-    case "$arg" in
         dylos.rt=*)
             val="${arg#dylos.rt=}"
             DST="${val%%,*}"
@@ -88,10 +83,20 @@ for arg in $CMDLINE; do
                     ;;
             esac
             ;;
+        dylos.fwd=1)
+            FWD=1
+            ;;
+        dylos.*)
+            echo "net-setup: error: unknown parameter $arg" >&2
+            exit 1
+            ;;
     esac
 done
 
 if [ "$FWD" = "1" ]; then
     sysctl -qw net.ipv6.conf.all.forwarding=1
     sysctl -qw net.ipv4.ip_forward=1
+else
+    sysctl -qw net.ipv6.conf.all.forwarding=0
+    sysctl -qw net.ipv4.ip_forward=0
 fi
